[build]
  publish = "."

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/brokercontrol"
  to = "/products/brokercontrol/"
  status = 301

[[redirects]]
  from = "/brokercontrol/"
  to = "/products/brokercontrol/"
  status = 301

[[redirects]]
  from = "/soc"
  to = "/products/soc/"
  status = 301

[[redirects]]
  from = "/soc/"
  to = "/products/soc/"
  status = 301

[[redirects]]
  from = "/cleanloop"
  to = "/products/cleanloop/"
  status = 301

[[redirects]]
  from = "/cleanloop/"
  to = "/products/cleanloop/"
  status = 301

[[redirects]]
  from = "/ghostwear"
  to = "/brands/ghostwear/"
  status = 301

[[redirects]]
  from = "/ghostwear/"
  to = "/brands/ghostwear/"
  status = 301
